### PR TITLE
Replace NPY_ARRAY_UPDATEIFCOPY with NPY_ARRAY_WRITEBACKIFCOPY

### LINKED ISSUE #100: Build error: undeclared identifier 'NPY_ARRAY_UPDATEIFCOPY'
When using the recent version of numpy (e.g. 1.23.5), `pip install git+https://github.com/dstndstn/tractor.git@main` fails with an error:
```
use of undeclared identifier 'NPY_ARRAY_UPDATEIFCOPY'
```
Replacing all occurrences of `NPY_ARRAY_UPDATEIFCOPY` with `NPY_ARRAY_WRITEBACKIFCOPY` cures the issue.

### PR DESCRIPTION
**Pull request by tgoldina**
Fix build error, closes #100

### CODE REVIEW

**Comment by dstndstn** [comment]
I'm not certain this is sufficient.  In Astrometry.net, we had to make changes like this

https://github.com/dstndstn/astrometry.net/commit/ae47640f8abe0593a2a757c2654201e650460445

where there's a `PyArray_ResolveWritebackIfCopy` call at the end of the function.

**Comment by tgoldina** [comment]
I'm afraid further changes are beyond my competence.

**Comment by dstndstn** [comment]
Ok -- I just tried doing this in 676f8fc75b8dd385559f29968821fa7675acb251 -- would you mind testing it?

**Comment by dstndstn** [comment]
Thank you for pointing out this issue!

**Comment by tgoldina** [comment]
There is one more file, where the update is needed: in [tractor/mix.i](https://github.com/dstndstn/tractor/blob/4b76636fa38e9d60b6ec2436a80488a19c224b15/tractor/mix.i) there are two more occurrences:

https://github.com/dstndstn/tractor/search?q=NPY_ARRAY_UPDATEIFCOPY

**Comment by dstndstn** [comment]
Oh, thanks for checking that!  Can you please try now?

**Comment by tgoldina** [comment]
Thank you very much. The install from main is successful.

**Pull request closed without merging**
