### PR TITLE
pixscale and decals-dir are now optional inputs

### PR DESCRIPTION
**Pull request by moustakas**
The title speaks for itself.  I tested the code a few different ways and wasn't able to break it, so hopefully this is mostly right.  decals_dir and the affiliated calibration directories are no longer global variables in common.py, but by initializing the Decals() class in DecamImage() class and passing forward decals_dir and the calibration directories everything seems to work OK.

The one thing I wasn't sure about in runbrick.py was the difference between initargs.update() and kwargs.update(), but I ended up using the former.

I'm also not sure how the code will die in Decals() if $DECALS_DIR *and* the optional input decals_dir are both not passed.  Right now there's a printed error message and not much more.

### CODE REVIEW

**Comment by moustakas** [comment]
Actually it looks like this doesn't work as advertised because the Decals() class is initialized (without the command-line argument!) every time DecamImage() is instantiated.  Thinking about a fix...

**Comment by moustakas** [comment]
A work-around I've come up with in lieu of passing decals-dir as an optional input is to call runbrick.py from within another python script using subprocess and changing $DECALS_DIR on the fly, which seems to work well.  To wit --
```python
env = os.environ.copy()                                                                                    
env['DECALS_DIR'] = /path/to/new/decals/dir                                                                    
runbrick = 'python {}/projects/desi/runbrick.py'.format(/path/to/tractor)                                       
cmd = '{} -b {} --threads {} --no-sdss --no-wise'.format(runbrick,brickname,args.threads).split()                                                           
ok = subprocess.check_call(cmd,cwd=/path/to/new/decals/dir,env=env)                                                 
```

**Comment by dstndstn** [comment]
Hi John,

Sorry for not replying earlier -- just back from vacation.

Another option would be to make it so that DecamImage always takes a Decals object in its constructor.  I am a bad person for having decals_dir be a global; it should live in the Decals object.  It should be possible, eg, to have DecamImage objects belonging to different Decals objects in the same process.

More broadly, "we" should probably pull out a "runbrick" function that takes the same set of options as the command-line args as runbrick.py, so it can easily be called from other python scripts.  You shouldn't have to use subprocess.  My bad.

I'm going to work on this refactor...

--dstn

**Comment by dstndstn** [comment]
Hi John,

Could you take a look at this now?  I added a function run_brick() to runbrick.py that should allow it to be called from other python code with roughly the same set of arguments as supported on the command-line.

Thanks for doing this -- good improvement!

--dstn

**Comment by moustakas** [comment]
TypeError: run_brick() got an unexpected keyword argument 'no_wise'

It's also not clear whether --no-sdss is being passed to run_brick()

Could we also have run_brick() return 1 or 0 if all went well so I can use an 'if' statement before moving the output files around?  (This is all very simulation-specific.)

**Comment by moustakas** [comment]
Sorry, I see it now.  I need 
wise=False,sdssInit=False

**Pull request merged**
